[package]
name = "game2048"
version = "0.1.0"
authors = ["0.382 <18322825326@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.5"
nix = "0.20.2"
